### ISSUE TITLE
schema is not updated

### ISSUE THREAD

**Issue by cskiwi** [exonest/graphql-cache-control#7]
hi,

I'm trying to figure out 2 things:
1) why my schema isn't adding the `@CacheControl` hints. 
2) why when mutating a object, the max-age of 0 isn't working, the max age is set for my queries.

this is my module:
```typescript
GraphQLModule.forRootAsync({
      driver: ApolloDriver,
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (config: ConfigService) => {
        return {
          playground: false,
          autoSchemaFile: join('schema/schema.gql'),
          csrfPrevention: true,
          cache: new KeyvAdapter(
            new Keyv({ 
              store: new KeyvRedis(
                new Redis({
                  db: 5,
                  host: config.get('CACHE_HOST'),
                  port: config.get<number>('CACHE_PORT'),
                  password: config.get('CACHE_PASSWORD'),
                })
              ),
            })
          ),
          context: ({ request }) => {
            return { req: request };
          },
          plugins: [
            ApolloServerPluginLandingPageLocalDefault({ embed: true }),
            ApolloServerPluginCacheControl({
              defaultMaxAge: config.get<number>('CACHE_DEFAULT_AGE'),
            }),
            responseCachePlugin(),
          ],
        } as Omit<GqlModuleOptions, 'driver'>;
      },
    }),
```

Any suggestions on why this is happening?

**Comment by cerpinn** [comment]
Hi @cskiwi, 

1. They won't end up in the generated GraphQL schema, but they are there and they *will* be applied. There was an issue in NestJS's repo on this I believe.
2. Make sure the parent object has max age of 0 as well. otherwise it won't work. I suggest you read through https://www.apollographql.com/docs/apollo-server/performance/caching/#in-your-resolvers-dynamic for more in-depth info about how the cache control works.
